# Generated by Django 3.0.14 on 2022-06-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_tete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tete',
        ),
    ]
