# Generated by Django 3.0.14 on 2022-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
