# Generated by Django 3.0.14 on 2022-06-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_super'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_super',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
